### ISSUE TITLE
SDK业务API地址在Windows环境错误

### ISSUE THREAD

**Issue by ssz66666** [larksuite/oapi-sdk-python#1]
# 问题描述
Windows环境下调用SDK业务时API URL拼接错误，提示 `resource not find`
# 环境
Windows 10 Python 3.8.8
# 示例
```python
from larksuiteoapi.service.contact.v3 import Service as ContactV3Service, User

from larksuiteoapi import Config, DOMAIN_FEISHU, DefaultLogger, LEVEL_DEBUG

app_settings = Config.new_internal_app_settings("AppID", "AppSecret", "VerificationToken", "EncryptKey")
from src.larksuiteoapi.service.contact.v3 import User

app_settings = Config.new_internal_app_settings_from_env()
conf = Config.new_config_with_memory_store(DOMAIN_FEISHU, app_settings, DefaultLogger(), LEVEL_DEBUG)

service = ContactV3Service(conf)
user = User()

service.users.get(user).do()
```
```
DEBUG: request http_path:https://open.feishu.cn/open-apis/contact/v3\users/, http_method:GET, access_token_type:tenant_access_token, request body:b''
DEBUG: Starting new HTTPS connection (1): open.feishu.cn:443
DEBUG: https://open.feishu.cn:443 "GET /open-apis/contact/v3%5Cusers/ HTTP/1.1" 404 43
DEBUG: request http_path:https://open.feishu.cn/open-apis/contact/v3\users/, response status code:404, response body:{'code': 99991201, 'msg': 'resource not find'}
```

# 建议
https://github.com/larksuite/oapi-sdk-python/blob/08f975c64bbda1f8c1babe113cd4b58eb899f80d/src/larksuiteoapi/service/contact/v3/api.py#L4
https://github.com/larksuite/oapi-sdk-python/blob/08f975c64bbda1f8c1babe113cd4b58eb899f80d/src/larksuiteoapi/service/contact/v3/api.py#L524

注意到SDK中使用了`os.path.join`来拼接URL，但在Windows环境下会默认使用`\`作为分隔符。
建议使用 `urllib.parse.urljoin` （python2 中为 `urlparse.urljoin` ）

**Comment by zhaoche27** [comment]
问题已解决，请升级SDK： pip install larksuite-oapi==1.0.6  

https://pypi.org/project/larksuite-oapi/

**Comment by zhaoche27** [comment]
service.users.get().set_user_id("用户OpenID").set_user_id_type("open_id").do()
