### ISSUE TITLE
larksuiteoapi.api.Request 不支持服务台API的token

### ISSUE THREAD

**Issue by ssz66666** [larksuite/oapi-sdk-python#12]
[飞书服务台API](https://open.feishu.cn/document/ukTMukTMukTM/ugDOyYjL4gjM24CO4IjN)要求在HTTP请求头中加入`X-Lark-Helpdesk-Authorization`字段。
> 请求中代入服务台token，表示拥有和服务台负责人相同的权限（查看修改服务台实体）。
> 使用方法,设置在请求Header中：
>
> - `Header Key: X-Lark-Helpdesk-Authorization`
> - `Header Value: base64(helpdesk_id:helpdesk_token)`, 通过base64加密将helpdesk_id和helpdesk_token用':'连接而成的字符串。

目前SDK中的`larksuiteoapi.api.Request`没有自定义header的选项。若调用服务台API，需要直接修改存在`larksuiteoapi.api.Request.session`的`requests.Session`对象的`headers`，暴露了其实现细节。

建议SDK在后续添加服务台API服务的支持，并优化Request对象的接口。

**Comment by zhaoche27** [comment]
谢谢你的反馈，这个能力我们应该会支持的。 支持了，会同步到这。

**Comment by zhaoche27** [comment]
已经支持了，请看 https://github.com/larksuite/oapi-sdk-python/blob/main/README.zh.md ，代码示例：https://github.com/larksuite/oapi-sdk-python/blob/main/sample/api/helpdesk.py

![image](https://user-images.githubusercontent.com/5029131/127165276-a6b0da4d-955d-406e-9ee2-c47c89c04e10.png)
