### ISSUE TITLE
怎么分别handle不同的消息卡片返回值？

### ISSUE THREAD

**Issue by Jinze10** [larksuite/oapi-sdk-python#26]
如果想有很多不同的消息卡片，如何区分它们呢？

**Comment by zhaoche27** [comment]
https://open.feishu.cn/document/ukTMukTMukTM/uYjNwUjL2YDM14iN2ATN

不同消息卡片不同的
"value":{
    "key-1":Object-1,
    "key-2":Object-2,
    "key-3":Object-3,
    	······
}
