### ISSUE TITLE
larkbot消息卡片多次发送

### ISSUE THREAD

**Issue by Jinze10** [larksuite/oapi-sdk-python#28]
当用户输入触发消息卡片发送时，消息卡片会发送多次，请问怎么解决呢？

**Comment by Jinze10** [comment]
可能用户只输入了一次，但相当于多次调用了处理接收到的消息的API，比如下面这样，这是什么原因呢？
![image](https://user-images.githubusercontent.com/99459428/159395133-ab2bcf93-7666-4180-b2ae-2ab64a1e1df4.png)

**Comment by zhaoche27** [comment]
截图是event 回调吧，与多次发送消息有啥关系， 你可以详细的说一下整个业务处理链路。 请求一次API，只会发送一条消息。

**Comment by Jinze10** [comment]
好像是因为处理时间过长导致的多次发送消息，已经解决，感谢！
