### ISSUE TITLE
消息卡片延迟更新返回 2200，Internal Error None

### ISSUE THREAD

**Issue by Jinze10** [larksuite/oapi-sdk-python#29]
调用 https://open.larksuite.com/document/ukTMukTMukTM/uMDO1YjLzgTN24yM4UjN 这个接口时返回2200，Internal Error None，请问怎么样解决呢？

**Comment by Jinze10** [comment]
传入的参数card是这样的格式：

{'title': '扣款结果', 'elements': [[{'tag': 'text', 'text': 'backend_order_id'}, {'tag': 'text', 'text': '\n42D13'}, {'tag': 'text', 'text': 'coupon_codes'}, {'tag': 'text', 'text': '\n2XSUMP'}, {'tag': 'text', 'text': 'force_collected'}, {'tag': 'text', 'text': '\nfalse'}, {'tag': 'text', 'text': 'return_deadline'}, {'tag': 'text', 'text': '\n2022-02-02'}, {'tag': 'text', 'text': 'product_name'}, {'tag': 'text', 'text': '\nOrka One Insider Program Canada'}, {'tag': 'text', 'text': 'shipped_time'}, {'tag': 'text', 'text': 'total_amount'}, {'tag': 'text', 'text': '\n0.0000'}, {'tag': 'text', 'text': 'discount_amount'}, {'tag': 'text', 'text': '\n0.0000'}], [{'tag': 'hr'}], [{'tag': 'text', 'text': '已提交审批流程'}]]}

**Comment by zhaoche27** [comment]
看看这个文档 https://open.feishu.cn/document/tools-and-resources/open-api-log-query  ，然后找飞书客服 oncall

**Comment by Jinze10** [comment]
好的，不过好像我的开发者后台看不到日志检索这个选项？它长这样：
![image](https://user-images.githubusercontent.com/99459428/159619218-367dc2cf-19f3-4dae-81f8-7865476d6e49.png)

**Comment by zhaoche27** [comment]
你给一下失败时的 reqeust_id 吧，如何获取 request_id ,  sdk readme 文档里有。 使用 request_id 更容易排查问题

**Comment by Jinze10** [comment]
> 你给一下失败时的 request_id 吧，如何获取 request_id , sdk readme 文档里有。 使用 request_id 更容易排查问题

request id = 20220323031449010100008074262622D4

**Comment by zhaoche27** [comment]
larksuite 我们还没有上 日志检索 能力，所以你还看不到

**Comment by zhaoche27** [comment]
https://open.feishu.cn/document/ukTMukTMukTM/ukTNwUjL5UDM14SO1ATN  你可以在仔细看看消息卡片的构造。

 'elements': [[ ，elements 应该是 一维数组 ，不是 二维

**Comment by Jinze10** [comment]
哦哦这样，谢谢啦！
