### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Loner-lyn** [larksuite/oapi-sdk-python#31]
在使用lark_sdk.get_sheets的时候，会报错Server_error，请问这样的问题如何解决？非常感谢！
![VAXhv8zuWd](https://user-images.githubusercontent.com/105416629/168016095-c87fa0cb-62ff-4710-9080-5f1bd28d2a44.jpg)

**Comment by zhailuxu** [comment]
请问现在恢复了？

**Comment by zhaoche27** [comment]
能提供一下 request_id 吗

**Comment by zhaoche27** [comment]
看一下 https://open.feishu.cn/document/tools-and-resources/open-api-log-query  ，提供一下有问题的日志中 的 x-log-id
