### ISSUE TITLE
sheet 追加数据 报forbidden

### ISSUE THREAD

**Issue by zhaibin** [larksuite/oapi-sdk-python#4]
req = Request('sheets/v2/spreadsheets/:spreadsheetToken/values_append','POST', ACCESS_TOKEN_TYPE_TENANT, valueRange,
                  request_opts=[set_path_params(path_params),set_query_params(query_params)])

报
{'code': 91403, 'data': {}, 'msg': 'Forbidden'}

在文档中https://open.feishu.cn/document/ukTMukTMukTM/ugjM14COyUjL4ITN  的错误描述是

91403 | FORBIDDEN | 没有权限 | 检查是否有文档读权限

我尝试读取sheet是可以读到的，但 写入 不成功。请大神指导

**Comment by malusama** [comment]
你得点击分享， 然后设置组织内得到连接的用户可编辑
![截屏2021-05-12 18 54 52](https://user-images.githubusercontent.com/7988608/117963985-a2ce0400-b353-11eb-858e-35cbd5df7621.png)

**Comment by zhaoche27** [comment]
问题解决了吗？

**Comment by zhaibin** [comment]
我后来是用user_token了。

**Comment by zhaoche27** [comment]
通过和sheets的开发者聊了一下，tenant_access_token 的支持，还在灰度之中，仅对部分租户可用。

**Comment by zhaibin** [comment]
> 通过和sheets的开发者聊了一下，tenant_access_token 的支持，还在灰度之中，仅对部分租户可用。

修改下网站上权限使用文档吧，只要是添加的数据的全部不能使用。
