### ISSUE TITLE
希望封装code2session接口

### ISSUE THREAD

**Issue by ssz66666** [larksuite/oapi-sdk-python#5]
SDK目前仅封装了用于H5 app的[access token接口](https://open.feishu.cn/document/ukTMukTMukTM/uEDO4UjLxgDO14SM4gTN)，而缺少用于与小程序交互的[code2session接口](https://open.feishu.cn/document/uYjL24iN/ukjM04SOyQjL5IDN)，希望能够添加。

**Comment by zhaoche27** [comment]
嗯，这是个好建议，后面可以加入SDK。

**Comment by zhaoche27** [comment]
先使用 SDK 的原生的方式 调用 哈。
