### ISSUE TITLE
SDK难以支持异步框架

### ISSUE THREAD

**Issue by ssz66666** [larksuite/oapi-sdk-python#6]
目前SDK中的API client接口固定使用requests，事件处理接口也定为使用回调函数，难以配合基于asyncio的异步web框架使用（如[Starlette](https://www.starlette.io/)、[FastAPI](https://fastapi.tiangolo.com/)）。
能否考虑添加基于asyncio的异步支持？或者将核心逻辑部分剥离出来，封装为非阻塞的组件（类似[h2](https://github.com/python-hyper/h2)）呢？

**Comment by zhaoche27** [comment]
能否考虑添加基于asyncio的异步支持？ 目前没有打算。

**Comment by ssz66666** [comment]
好的，谢谢解答
