### ISSUE TITLE
How to use `filter`?

### ISSUE THREAD

**Issue by threehappyer** [larksuite/oapi-sdk-python#62]
https://open.feishu.cn/document/server-docs/docs/bitable-v1/app-table-record/list

Demo里示例
```
        .filter("AND(CurrentValue.[身高]>180, CurrentValue.[体重]>150)") 
```
但是完全没有可参考性. 我不知道这个fields都有哪些.

```
    "fields": {
        "created_at": 1704206701000,
        "created_date": [
            {
                "text": "2024/01/02",
                "type": "text"
            }
        ],
...
}
```
以上述fields为例, 我需要过滤 created_date等于2024/01/02, 要如何写这个filter?

**Comment by maemual** [comment]
详情可见开发文档：https://open.larkoffice.com/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-record/record-filter-guide
