### ISSUE TITLE
使用长连接模式订阅事件 实例运行报错 

### ISSUE THREAD

**Issue by nonpricklycactus** [larksuite/oapi-sdk-python#63]
![66b1bd28-73be-4356-85ba-e724c08e9ff4](https://github.com/larksuite/oapi-sdk-python/assets/36537993/8a9a959b-b98d-41dc-bae4-9426aeff62b2)
报错：AttributeError: module 'lark_oapi' has no attribute 'ws'. Did you mean: 'os'?

环境：
![51e7819f-9704-40ba-bb9b-6295e8fc5ffe](https://github.com/larksuite/oapi-sdk-python/assets/36537993/026e43c0-ab93-4561-9fcd-2a755f2de2b2)

代码为示例代码：
https://github.com/larksuite/oapi-sdk-python/blob/v2_main/samples/ws/sample.py

**Comment by WRCoding** [comment]
你好，我也报这个错，最后是怎么解决的呢
