### ISSUE TITLE
卡片回调的_verify函数存在问题

### ISSUE THREAD

**Issue by IronVector** [larksuite/oapi-sdk-python#76]
飞书文档里描述安全验证需要ENCRYPT_KEY和sha256作为哈希函数运算，然后和飞书header里的签名做验证。但是CardActionHandler里_verify函数的实现方式是利用VERIFICATION_TOKEN和sha1函数运算，导致签名无法通过验证。
此外，解密方法也有问题，安全验证后，无法把body解密

**Comment by maemual** [comment]
你看到的是新版的卡片回传交互。SDK 目前支持的是旧版，新版会在这个 Q 尽快支持一下。

**Comment by IronVector** [comment]
奥奥，行。等待新版的sdk发版



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 14:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [larksuite/oapi-sdk-python] 卡片回调的_verify函数存在问题 (Issue #76) |

你看到的是新版的卡片回传交互。SDK 目前支持的是旧版，新版会在这个 Q 尽快支持一下。

**Comment by maemual** [comment]
现在建议先用「消息卡片回传交互（旧）card.action.trigger_v1」，同时搭配 sdk >= 1.3.0 版本。

**Comment by IronVector** [comment]
嗯，用上了，现在调通了。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 15:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [larksuite/oapi-sdk-python] 卡片回调的_verify函数存在问题 (Issue #76) |

现在建议先用「消息卡片回传交互（旧）card.action.trigger_v1」，同时搭配 sdk >= 1.3.0 版本。

**Comment by apan-liu** [comment]
有用，用旧版本的回调，不需要更新解密函数

**Comment by maemual** [comment]
1.4.0 之后已支持 card.trigger.action 新回调。
