### ISSUE TITLE
希望可以通过长链接的方式支持回调订阅

### ISSUE THREAD

**Issue by a1342966673** [larksuite/oapi-sdk-python#86]
如题🥳

**Comment by maemual** [comment]
Golang 和 Nodejs 的版本已经在内测中了，Python 和 Java 的预期这个月会发布。

**Comment by a1342966673** [comment]
> Golang 和 Nodejs 的版本已经在内测中了，Python 和 Java 的预期这个月会发布。

ws将支持新版的卡片回调吗

**Comment by maemual** [comment]
> > Golang 和 Nodejs 的版本已经在内测中了，Python 和 Java 的预期这个月会发布。
> 
> ws将支持新版的卡片回调吗

是的，将同期一块支持新版的卡片回调。

**Comment by a1342966673** [comment]
> > > Golang 和 Nodejs 的版本已经在内测中了，Python 和 Java 的预期这个月会发布。
> > 
> > 
> > ws将支持新版的卡片回调吗
> 
> 是的，将同期一块支持新版的卡片回调。

wow～那么我从哪里可以接收到更新通知呢，有没有发布群类似的地方

**Comment by maemual** [comment]
> > > > Golang 和 Nodejs 的版本已经在内测中了，Python 和 Java 的预期这个月会发布。
> > > 
> > > 
> > > ws将支持新版的卡片回调吗
> > 
> > 
> > 是的，将同期一块支持新版的卡片回调。
> 
> wow～那么我从哪里可以接收到更新通知呢，有没有发布群类似的地方

README 最底下放了 SDK 的交流群链接。

**Comment by maemual** [comment]
1.4.0 之后已支持。
