### ISSUE TITLE
Config.new_internal_app_settings_from_env 误检查ENCRYPT_KEY是否存在

### ISSUE THREAD

**Issue by ssz66666** [larksuite/oapi-sdk-python#9]
https://github.com/larksuite/oapi-sdk-python/blob/b514d80a88b046f9386b0583e7b347bfc01a9c5b/src/larksuiteoapi/config.py#L45-L46
此处应改为
```python
if app_secret == '':
    raise RuntimeError('environment variables not exist `APP_SECRET`')
````

**Comment by zhaoche27** [comment]
谢谢反馈，会在下一个版本，修复掉。

**Comment by zhaoche27** [comment]
已经修复：pip install larksuite-oapi==1.0.24rc1
